# Project information
site_name: RMK
site_description: RMK CLI - Reduced Management for Kubernetes by Edenlab LLC.
# todo change to static domain
site_url: https://edenlabllc.github.io/rmk

copyright: © EDENLAB. ALL RIGHTS RESERVED, 2021 - 2024

# Extra Files
extra_javascript:
  - static/js/asciinema-player.js

extra_css:
  - static/css/asciinema-player.css
  - static/css/extra.css

# Repo Information
repo_name: edenlabllc/rmk
repo_url: https://github.com/edenlabllc/rmk

# Edit Link on Site
#edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  language: en
  features:
    - navigation.top # show back to top button
    - search.suggest # search suggestions: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.highlight # highlight search term on target page: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky # stick navigation tabs below header while scrolling
    - navigation.tracking
    - navigation.path
# todo review list of features
#    - navigation.instant
#    - navigation.sections
#    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "black"
      accent: "grey"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # todo change icons and logo
  logo: https://edenlab.io/wp-content/themes/edenlab/assets/images/fhir_icon.svg
  favicon: https://edenlab.io/favicon.ico
  icon:
    repo: fontawesome/brands/github

# Navigation
# nav: omitted, because we're using the awesome-pages plugin (https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/)

# Extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
      use_pygments: true
  - pymdownx.inlinehilite # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#inlinehilite
  - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#superfences
  - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#tabbed
  - pymdownx.details # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#details
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - smarty # https://python-markdown.github.io/extensions/smarty/
  - mdx_truly_sane_lists # https://github.com/radude/mdx_truly_sane_lists -> proper indentation of md list items

# Plugins
plugins:
  - search
  - git-revision-date-localized: # https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
      type: date
  - awesome-pages    # https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - mike:            # Versioned Docs: https://github.com/jimporter/mike
      version_selector: true    # set to false to leave out the version selector
      css_dir: static/css       # the directory to put the version selector's CSS
      javascript_dir: static/js # the directory to put the version selector's JS
      canonical_version: null   # the version for <link rel="canonical">; `null` uses the version specified via `mike deploy`

# Extra mkdocs-material settings
extra:
  version:
    provider: mike

# Other Settings
strict: true # halt processing when a warning is raised
