name: Feature request
description: Describe a new feature.
labels: [enhancement]
projects:
  - edenlabllc/43
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! Please fill the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your issue here.
    validations:
      required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Agree to the Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/edenlabllc/rmk/blob/master/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
