name: Build, validate, publish, version documentation for GitHub Pages

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Build, validate, publish, version documentation for GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: pip install -r docs/requirements.txt

      - name: Build, validate documentation using MkDocs
        run: |
          mkdocs build --verbose --clean --strict
          rm -r site/

      - name: Build, publish, version documentation using Mike (only for stable tags)
#        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Configure Git user.name and user.email."
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # VERSION=${GITHUB_REF#refs/tags/}
          VERSION=v0.43.0
          
          mike deploy --update-aliases --push --rebase "${VERSION}" latest
